### ISSUE TITLE
Classes for Table Items

### ISSUE THREAD

**Issue by harryShepherd** [harryShepherd/Ambry#37]
In the branch `feature/db-interaction` , several classes are needed for the databases. These include:
```
City:
- ID
- Name
- CountryCode
- District
- Population
```

```
County:
- Code
- Name
- Continent
- Region
- SurfaceArea
- Indepyear
- Population
- LifeExpectancy
- GNP
- GNPOld
- LocalName
- GovernmentForm
- HeadOfState
- Capital
- Code2
```

```
CountryLanguage:
- CountryCode
- Language
- IsOfficial
- Percentage
```

**Comment by MurdoWa** [comment]
completed for country:

https://github.com/harryShepherd/Ambry/blob/feature/db-interaction/src/main/java/com/napier/Ambry/Country.java

**Comment by MurdoWa** [comment]
completed for countyLanguage:

https://github.com/harryShepherd/Ambry/blob/feature/db-interaction/src/main/java/com/napier/Ambry/CountryLanguage.java

**Comment by harryShepherd** [comment]
THANK you murdo wa
