### ISSUE TITLE
City Standard Epic 3

### ISSUE THREAD

**Issue by Alcor2814** [harryShepherd/Ambry#47]
The city standard in Epic 3 needs to retrieve the country of the city but as yet cannot.

**Comment by Alcor2814** [comment]
public static ArrayList<City> CityStandard(String select){
        ArrayList<City> Cities = new ArrayList<City>();

        try {
            Statement stmt = Database.con.createStatement();
            ResultSet rset = stmt.executeQuery(select);

            while (rset.next()) {
                City city = new City();
                city.setName(rset.getString("city.Name"));
                //Need to store Country
                city.setDistrict(rset.getString("city.District"));
                city.setPopulation(rset.getInt("city.Population"));

                Cities.add(city);
            }
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }

        return Cities;
    }

**Comment by harryShepherd** [comment]
i think the city table only stores the country code, so you can maybe use that and make a function to get a country by country code?

**Comment by Alcor2814** [comment]
I'm not sure what the best method for doing and then displaying that would be then

**Comment by harryShepherd** [comment]
Something like
`Country getCountryByCode(string code)`
Or something?

**Comment by MurdoWa** [comment]
added the function, its in epic 3
